[versions]
agp = "8.11.1"
kotlin = "2.1.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
composeBom = "2025.06.01"
appcompat = "1.7.1"
material = "1.12.0"
hilt = "2.56.2"
hiltNavigationCompose = "1.2.0"
ksp = "2.1.21-2.0.1"
coreSplashscreen = "1.0.1"
okhttp = "5.0.0-alpha.16"
retrofit = "3.0.0"
gson = "2.11.0"
room = "2.7.2"
utilcodex = "1.31.1"
navigation-compose = "2.9.0"
coil = "3.2.0"
preferences="1.1.7"
webkit="1.14.0"
pag="4.4.35"
desugarJdkLibs = "2.0.4"
rxjava3 = "3.1.6"
rxandroid = "3.0.0"
rxandroidble = "1.19.1"
glasses="1.0.4"
media3 = "1.3.1"
preference = "1.2.1"
libvlc = "3.6.5"
instavision-ffmpeg = "2025.08.21"
volcengine-douyin = "3.1.1"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3-icons = { group = "androidx.compose.material", name = "material-icons-extended-android" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-datastore-preferences={group="androidx.datastore",name="datastore-preferences",version.ref="preferences"}
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }

#Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

#network
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gson" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }

#util
utilcodex = { group = "com.blankj", name = "utilcodex", version.ref = "utilcodex" }

#coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video", version.ref = "coil" }

#web
webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }

#libpag
libpag = { group = "com.tencent.tav", name = "libpag", version.ref = "pag" }

android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

#Rxble
rxjava3 = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava3" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
rxandroidble = { group = "com.polidea.rxandroidble3", name = "rxandroidble", version.ref = "rxandroidble" }

#glasses
glasses-sdk = { group = "com.fission.wear.glasses", name = "sdk", version.ref = "glasses" }

#live
libvlc = { group = "org.videolan.android", name = "libvlc-all", version.ref = "libvlc" }
instavision-ffmpeg = { group = "ai.instavision", name = "ffmpegkit", version.ref = "instavision-ffmpeg" }
volcengine-douyin-sdk = { group = "com.volcengine.android", name = "douyin_sdk", version.ref = "volcengine-douyin" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize" }

[bundles]
coil = ["coil-compose", "coil-network-okhttp","coil-video"]
media3 = ["androidx-media3-common", "androidx-media3-exoplayer", "androidx-media3-ui"]